### PR TITLE
[Cadence] Allow specifying annotations on services

### LINKED ISSUE #1303: [Cadence] Chart doesn't allow passing annotations or labels to services
**Describe the bug**
When configuring the Cadence chart on EKS using the AWS Load Balancer Controller, we need to be able to set annotations on the services. The chart doesn't currently allow setting additional annotations. 

**Steps to reproduce the issue:**
N/A

**Expected behavior**
The chart allows deploying additional annotations on services. 

**Screenshots**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by johnkost**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #1303 
| License         | Apache 2.0

### What's in this PR?
Allows passing in additional annotations to the services created by cadence

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Review by sagikazarmark — APPROVED** [review]
LGTM

**Review by pregnor — APPROVED** [review]

**Comment by johnkost** [comment]
@sagikazarmark @pregnor - Thanks for the approvals! I don't have `write` access so I can't merge this. Can one of you merge this?

**Comment by pregnor** [comment]
Sure, I can do that later today.

Would you prefer waiting for your other PR and release the 2 changes in a single version or should I release them separately as soon as merged?

**Comment by johnkost** [comment]
> Sure, I can do that later today, I am finishing up the manual pre-release tests.
> 
> Would you prefer waiting for your other PR and release the 2 changes in a single version or should I release them separately as soon as merged?

Lets do individual. I still need to make changes to the other one. Thank you!

**Comment by pregnor** [comment]
In that case please also don't forget to bump the patch version number in your second PR.

**Pull request merged**
