### PR TITLE
[thanos] Fixed bugs in thanos rules

### PR DESCRIPTION
**Pull request by ahmednasir91**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | N/A
| License         | Apache 2.0

### What's in this PR?
There are two issues
- in the rule labels since we are using the `quote` function to add quotes then using single quotes for the definition. Without it was causing the error `YAML parse error on thanos/templates/rule-statefulset.yaml: error converting YAML to JSON: yaml: line 44: did not find expected key`
- the config volume for rules had issues with related to field spacing so the output when the `ruleNameOverride` is empty was `configMap:name:` with missing newline and with the fix it is 
```
configMap:
  name: ...
```
- the query dns discovery uses the protocol grpc but the service url was using http instead of grpc.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by Sasasu** [comment]
Hi, banzaicloud.

I find another bug in the Thanos Helm chart.

In `rule-statefulset.yaml`, `-http` should be `-grpc`

```diff
diff --git a/thanos/templates/rule-statefulset.yaml b/thanos/templates/rule-statefulset.yaml
index a64237f..f4bbfcd 100644
--- a/thanos/templates/rule-statefulset.yaml
+++ b/thanos/templates/rule-statefulset.yaml
@@ -81,7 +81,7 @@ spec:
         - "--web.prefix-header={{ .Values.rule.webPrefixHeader }}"
         {{- end }}
         {{- if .Values.rule.queryDNSDiscovery }}
-        - "--query=dnssrv+_grpc._tcp.{{ include "thanos.componentname" (list $ "query") }}-http.{{ .Release.Namespace }}.svc.cluster.local"
+        - "--query=dnssrv+_grpc._tcp.{{ include "thanos.componentname" (list $ "query") }}-grpc.{{ .Release.Namespace }}.svc.cluster.local"
         {{- end  }}
         {{- range .Values.rule.alertmanagers }}
```

**Comment by ahmednasir91** [comment]
> Hi, banzaicloud.
> 
> I find another bug in the Thanos Helm chart.
> 
> In `rule-statefulset.yaml`, `-http` should be `-grpc`
> 
> ```diff
> diff --git a/thanos/templates/rule-statefulset.yaml b/thanos/templates/rule-statefulset.yaml
> index a64237f..f4bbfcd 100644
> --- a/thanos/templates/rule-statefulset.yaml
> +++ b/thanos/templates/rule-statefulset.yaml
> @@ -81,7 +81,7 @@ spec:
>          - "--web.prefix-header={{ .Values.rule.webPrefixHeader }}"
>          {{- end }}
>          {{- if .Values.rule.queryDNSDiscovery }}
> -        - "--query=dnssrv+_grpc._tcp.{{ include "thanos.componentname" (list $ "query") }}-http.{{ .Release.Namespace }}.svc.cluster.local"
> +        - "--query=dnssrv+_grpc._tcp.{{ include "thanos.componentname" (list $ "query") }}-grpc.{{ .Release.Namespace }}.svc.cluster.local"
>          {{- end  }}
>          {{- range .Values.rule.alertmanagers }}
> ```

Hi @Sasasu thanks for reporting, I've added the fix in this PR.

**Comment by Sasasu** [comment]
Hi, banzaicloud.
I find another bug in the Thanos Helm chart. again.

the Thanos rule has an Ingress config in `value.yaml` but not generate the `rule-ingress.yaml`

Thanos rule has a web UI, which can display some useless information. but I think it’s better to let users configure it.

**Review by tarokkk — APPROVED** [review]

**Comment by giovannirco** [comment]
> Hi, banzaicloud.
> I find another bug in the Thanos Helm chart. again.
> 
> the Thanos rule has an Ingress config in `value.yaml` but not generate the `rule-ingress.yaml`
> 
> Thanos rule has a web UI, which can display some useless information. but I think it’s better to let users configure it.

did someone look into this? just found this issue as well

**Comment by ahmednasir91** [comment]
@giovannirco @Sasasu i've done it in my local fork, will send a PR for it.

**Pull request merged**
