### PR TITLE
fix query frontend downstream URL

### PR DESCRIPTION
**Pull request by mstrzele**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
The PR contains a change for the `query-frontend-downstream-url` parameter's value.

### Why?
The change removes `.svc.cluster.local` from the URL, so after the change, it will point to a service without specifying a namespace nor a cluster domain.

### Checklist
- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by psandhu79** [comment]
Should this not include {{ .Release.Namespace }}

        - "--query-frontend.downstream-url=http://{{ include "thanos.componentname" (list $ "query") }}-http.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.query.http.port }}"

**Comment by mstrzele** [comment]
> Should this not include {{ .Release.Namespace }}
> 
> ```
>     - "--query-frontend.downstream-url=http://{{ include "thanos.componentname" (list $ "query") }}-http.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.query.http.port }}"
> ```

Both `query` service and `query-frontend` deployment are in the same namespace thus adding it to the URL is redundant.

**Comment by mstrzele** [comment]
Hi @ahma,

Could you take a look at this simple fix? It's been a while since I've created a PR and it would be nice to have it fixed in the upstream chart.

**Comment by paranoidsp** [comment]
Noticed the same issue, and this should fix it. Needs a bump to the chart version though.

**Comment by paranoidsp** [comment]
@ahma apologies for tagging you, but you seem to have the last commit on the thanos chart, would it be possible to get a review here and a merge?

**Review by ahma — APPROVED** [review]
LGTM! Thanks @mstrzele

**Comment by paranoidsp** [comment]
Thank you @ahma @mstrzele !

**Pull request merged**
