### PR TITLE
vault operator version 0.4.7, new operator flags, serviceAccount/Name

### PR DESCRIPTION
**Pull request by raoofm**

### CODE REVIEW

**Comment by bonifaido** [comment]
Hi @raoofmz thanks

**Comment by raoofm** [comment]
@bonifaido seems you closed it without merging, do you see any issue?

**Comment by bonifaido** [comment]
Sorry, was just a mistake.

**Comment by raoofm** [comment]
never mind

**Comment by raoofm** [comment]
@bonifaido I'm not using etcd right now, but I did check the release logs and doesn't seem like anything could impact. Do you want me to revert etcd-operator version change

**Comment by raoofm** [comment]
@bonifaido i reverted etcd operator version and also added one more fix where crd annotations had incorrect spacing

**Comment by bonifaido** [comment]
I have no objections against updating etcd-operator, just wanted to make sure it still works with the vault-operator, anyhow one can use a newer version via setting custom values. Thanks for the updates!

**Pull request merged**
