### PR TITLE
Add affinity templating to dex

### PR DESCRIPTION
**Pull request by bartlettt**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | no
| License         | Apache 2.0

### What's in this PR?
The dex templated affinity value is rendered. Apologies for the double PR, I realised I'd missed the rendering after it got merged. 

### Why?
This allows the user to define labels, which themselves have been templated. This is crucial for affinity to be set correctly. Example:
```
# Prefer pods to run across all three AZs
affinity: |
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
        matchLabels:
          app: {{ template "dex.name" . }}
          release: {{ .Release.Name }}
        topologyKey: failure-domain.beta.kubernetes.io/zone
```

### Checklist

- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [x] Logging code meets the guideline (TODO)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by bonifaido** [comment]
No problem.

But linting fails now with:
```
==> Linting /root/project/./dex
[ERROR] templates/: render error in "dex/templates/deployment.yaml": template: dex/templates/deployment.yaml:33:23: executing "dex/templates/deployment.yaml" at <.Values.affinity>: wrong type for value; expected string; got map[string]interface {}
```

**Comment by bartlettt** [comment]
I've reworked the rendering for the linter. An example input would now be one multiline string:
```
affinity: |
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
        matchLabels:
          app: {{ template "dex.name" . }}
          release: {{ .Release.Name }}
        topologyKey: failure-domain.beta.kubernetes.io/zone
```

**Comment by bonifaido** [comment]
It might be worth to mention that this can be a template as well in the parameters table.

**Comment by bartlettt** [comment]
I've updated the readme and added an example

**Pull request merged**
