### PR TITLE
Thanos query frontend

### LINKED ISSUE #1139: Query frontend support for Thanos chart
Hi, I would like to see addition of Thanos [query frontend](https://thanos.io/components/query-frontend.md/) to the chart.

### PR DESCRIPTION
**Pull request by bueti**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #1139 
| License         | Apache 2.0

### What's in this PR?

This PR adds support for the [Thanos Query Frontend](https://thanos.io/v0.17/components/query-frontend.md/)

Not supported
* Memcached
* Cache config by file

### Why?

Because this is really useful to not have the store/querier crash

### Additional context

This is my first PR here :) Please let me know if something important is missing.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by wiardvanrij** [comment]
Thanks so much, I was looking for this.
My personal feedback (I'm not a reviewer here, just a friendly bypasser :D )

- I'm missing the part for autoscaling. - The actual file for the HorizontalPodAutoscaler
- The URL for --query-frontend.downstream-url, which is now a var, could be found by using something as 
```
http://{{ include "thanos.componentname" (list $ "query") }}-http.svc.cluster.local:{{ .Values.query.http.port }}
```
See the query component as reference.

- I'm missing the label arguments such as `--labels.X` and also configuration options for it, regarding the cache options for the frontend-cache. See the thanos docs for all arguments.
- I would love to see some option to include a config file for MEMCACHED (or MEMORY too for that matter).  Perhaps via configmap or atleast dynamic configurable via the helm values.

**Comment by bueti** [comment]
> Thanks so much, I was looking for this.
> My personal feedback (I'm not a reviewer here, just a friendly bypasser :D )
> 
>     * I'm missing the part for autoscaling. - The actual file for the HorizontalPodAutoscaler
> 
>     * The URL for --query-frontend.downstream-url, which is now a var, could be found by using something as
> 
> 
> ```
> http://{{ include "thanos.componentname" (list $ "query") }}-http.svc.cluster.local:{{ .Values.query.http.port }}
> ```
> 
> See the query component as reference.
> 

Thanks for the feedback! I've added the missing configuration and the automated downstream url.

>     * I'm missing the label arguments such as `--labels.X` and also configuration options for it, regarding the cache options for the frontend-cache. See the thanos docs for all arguments.
> 

I'll check this later today.

>     * I would love to see some option to include a config file for MEMCACHED (or MEMORY too for that matter).  Perhaps via configmap or atleast dynamic configurable via the helm values.

No promises here, so far we are not using Memcached but if I have some spare time I'll have a look at it later this week.

**Comment by bueti** [comment]
>     * I'm missing the label arguments such as `--labels.X` and also configuration options for it, regarding the cache options for the frontend-cache. See the thanos docs for all arguments.

added.

**Comment by galexrt** [comment]
When having set `queryFrontend.rbac.enabled: true` I get the following error:
```
Error: UPGRADE FAILED: template: thanos/templates/query-frontend-rbac.yaml:50:11: executing "thanos/templates/query-frontend-rbac.yaml" at <include "thanos.queryFrontend.serviceaccount" .>: error calling include: template: no template "thanos.queryFrontend.serviceaccount" associated with template "gotpl"
```

I still need to look further into why this happens, but I thought I'll post it here already.

**Comment by bueti** [comment]
> When having set `queryFrontend.rbac.enabled: true` I get the following error:
> 
> ```
> Error: UPGRADE FAILED: template: thanos/templates/query-frontend-rbac.yaml:50:11: executing "thanos/templates/query-frontend-rbac.yaml" at <include "thanos.queryFrontend.serviceaccount" .>: error calling include: template: no template "thanos.queryFrontend.serviceaccount" associated with template "gotpl"
> ```
> 
> I still need to look further into why this happens, but I thought I'll post it here already.

I missed some templating, the last commit should fix that.

**Comment by bueti** [comment]
Anybody home? @tarokkk @ahma

**Review by tarokkk — APPROVED** [review]

**Comment by tarokkk** [comment]
Thanks for the awesome contribution. We had things to deal with :) but reviewing now.

**Review by ahma — APPROVED** [review]
LGTM Thanks @bueti, sorry for the delay

**Pull request merged**
