### PR TITLE
add optional vault cr

### PR DESCRIPTION
**Pull request by raoofm**
relates to #574

### CODE REVIEW

**Comment by raoofm** [comment]
@bonifaido this is the way i'm using the chart. As I mentioned in #574 normally operators allow creation of the CR as well but this piece was missing earlier.

**Comment by raoofm** [comment]
sorry for multiple commits - you can squash it.

**Comment by raoofm** [comment]
probably i should comment out all the resources, vault config and external configs and leave it up to the user to define as needed.

**Comment by raoofm** [comment]
@bonifaido checked the ci failure, not sure if it is related

Error: kafka chart not found in repo http://kubernetes-charts.banzaicloud.com/branch/pull/680/
Exited with code 1

**Comment by bonifaido** [comment]
Hi @raoofm, we are checking the build, sorry for the inconvenience.

**Comment by bonifaido** [comment]
Thanks for the contribution @raoofm  

Reflecting to:
>  probably i should comment out all the resources, vault config and external configs and leave it up to the user to define as needed.

I think the CRD should be very generic and should be installable out of the box in the first time if it is enabled via vanilla config, which is not the case currently in this CRD. Could you please fix this?

**Comment by bonifaido** [comment]
Build fixed in the meantime, you have created your branch in the point of time, where the build was broken, I have rebased it on the latest master where it is already fixed.

**Comment by raoofm** [comment]
> I think the CRD should be very generic and should be installable out of the box in the first time if it is enabled via vanilla config, which is not the case currently in this CRD. Could you please fix this?

sure, will do it soon

**Comment by l13t** [comment]
hi all
any updates on this pr?

**Comment by bonifaido** [comment]
Closing this for now, we can revisit this in the future, but since Helm doesn't handle CRD and CR installation in the same chart really well (we and our users encountered this issue many times) I suggest creating another (umbrella) chart which pulls in the operator and then installs a Vault CR.

For creating and hosting public Helm charts I can offer https://charts.banzaicloud.io/ which is a free Chart repository as a service (based on ChartMuseum).

**Pull request closed without merging**
